# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3be920a71b840289f7ae3c0abfd4a011a3b444adc985e3cc2b906d09ffd604c8c6124bb4bda051102e5334c35a1e93715acd43ef05cda02beb618832d87dade

test:
  secret_key_base: 74e22c4fc6eb496b7b923c6779d5d20042b8a7caa0cfcf66fec08c6f3a28a5f3373cd239a1e6480397713b596953d82bff2c78224d101af5e1cc1bdb0dd7e593

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
